global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'video_generation'
    static_configs:
      - targets: ['localhost:8082']
        labels:
          service: 'video_generation'

  - job_name: 'system_metrics'
    static_configs:
      - targets: ['localhost:8083']
        labels:
          service: 'system_metrics'
